create table sneakers (
  id bigint generated by default as identity primary key,
  name text not null,
  brand text not null,
  price int not null,
  description text,
  image text
);

insert into sneakers (name, brand, price, description, image)
values ('Air Force 1 - Van Gogh Starry Night', 'Nike', 350, 'Een meesterwerk aan je voeten.', '/images/Nike_Air_Force_1_van_gogh.jpeg'),
        ('Air Max 90 - cyberpunk', 'Nike', 300, 'Een futuristische twist op een klassieker, geïnspireerd door de cyberpunk esthetiek.', '/images/Nike_Air_Max_90_cyberpunk.jpeg'),
        ('Old Skool - Piet Mondriaan', 'Vans', 250, 'Een eerbetoon aan de abstracte kunst van Piet Mondriaan.', '/images/Vans_Old_Skool_Piet_Mondriaan.jpeg'),
        ('Chuck Taylor - Super Mario Bros.', 'Converse', 250, 'Een klassieke sneaker met een super Mario Bros. thema.', '/images/Converse_Chuck_Taylor_Super_Mario_Bros.jpeg'),
        ('Air Force 1 - pacman', 'Nike', 300, 'Een nostalgische sneaker geïnspireerd op het iconische Pac-Man spel.', '/images/Nike_Air_Force_1_pacman.jpeg'),
        ('Stan Smith - Nature', 'Adidas', 150, 'Een milieuvriendelijke versie van de klassieke Stan Smith, gemaakt van gerecyclede materialen.', '/images/Adidas_Stan_Smith_nature.jpeg'),
        ('Slip-On - Japanese Art', 'Vans', 300, 'Een unieke sneaker met een ontwerp geïnspireerd op traditionele Japanse kunst.', '/images/Vans_Slip-On_japanese_art.jpeg'),
        ('Dunk Low - Cartoon', 'Nike', 250, 'Een unieke sneaker met een cartoon-ontwerp.', '/images/Nike_Dunk_Low_cartoon.jpeg');

select * from sneakers;